### ISSUE TITLE
Error: Could not resolve type with token 01000016 from typeref (expected class 'Cake.Core.CakeTaskBuilder`1' in assembly 'Cake.Core, Version=0.26.1.0, Culture=neutral, PublicKeyToken=null')

### ISSUE THREAD

**Issue by cosminstirbu** [Redth/Cake.Xamarin.Build#4]
Hello.

It seems that the current Cake.Xamarin.Build version is not compatible with the latest Cake version (0.31.0).

As per https://github.com/cake-build/cake/issues/2264#issuecomment-418079995 it seems that Cake 0.28.0 removed a type that Cake.Xamarin.Build is relying on.

Can you please have a look?

Thanks,
Cosmin

**Comment by Redth** [comment]
This has been updated to 0.33 of cake.
